version: '3'
services:
  v_serve_proxy:
    image: nginx:latest
    container_name: v_serve_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./site/public_html:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    links:
      - v_serve_web
    restart: always
  v_serve_web:
    container_name: v_serve_web
    build:
      context: .
      dockerfile: phpfpm/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./certs/live/phuket.weserve.co.th/fullchain.pem:/usr/lib/ssl/cert.pem
      - ./phpfpm/php.ini-development:/usr/local/etc/php/php.ini
      - ./phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./site/public_html:/var/www/html
      - ./site/public_html/media:/var/www/html/media
      - ./site/public_html/cache:/var/www/html/application/cache
      - ./site/public_html/config:/var/www/html/application/config
    external_links:
      - 'v_serve_db:v_serve_db'
    extra_hosts:
      - 'v_serve_db:10.140.0.2'
    restart: always

